name: torch-brain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pytorch_brain
    - lightning
    - torch
    - numpy
    - matplotlib
    - scikit-learn
    - tqdm
