name: decoder-data-format
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip:
    - jupytext
    - numpy
    - scipy
    - matplotlib
    - tqdm
    - opencv-python
    - scikit-learn
    - torch
    - torchvision
    - h5py
    - ipykernel
    - pandas
    - dandi
    - ONE-api
    - pynwb
    